List<String> templates = [
    'assets/0.png',
    'assets/6.png',
    'assets/2.png',
    'assets/4.png',
    'assets/3.png',
    'assets/5.png',
    'assets/2.png',
    'assets/7.png',
    'assets/8.png',
    'assets/9.png',
    'assets/10.png',
    'assets/11.png',
    'assets/12.png',
    'assets/0.png',
    'assets/1.png',
    'assets/2.png',
    'assets/3.png',
    'assets/4.png',
    'assets/5.png',
    'assets/6.png',
    'assets/7.png',
    'assets/8.png',
    'assets/9.png',
    'assets/10.png',
    'assets/11.png',
    'assets/12.png',
  ];

  List<String> templatesName = [
    'neat',
    'creative',
    'modern',
    'Template 4',
    'Template 5',
    'Template 6',
    'Template 7',
    'Template 8',
    'Template 9',
    'Template 10',
    'Template 11',
    'Template 12',
    'Template 1',
    'Template 2',
    'Template 3',
    'Template 4',
    'Template 5',
    'Template 6',
    'Template 7',
    'Template 8',
    'Template 9',
    'Template 10',
    'Template 11',
    'Template 12',
    'Template 13',
    'Template 14',
  ];